// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace ShaderTest
{
    public static partial class MyDiffuseKeys
    {
        public static readonly ValueParameterKey<Color3> myFallbackColor = ParameterKeys.NewValue<Color3>(new Color3(0.3f,1.0f,0.6f));
        public static readonly ObjectParameterKey<Texture> myTex = ParameterKeys.NewObject<Texture>();
        public static readonly ValueParameterKey<Color3> myColor = ParameterKeys.NewValue<Color3>(new Color3(0.8f,0.1f,0.2f));
    }
}
