// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace ShaderTest
{
    public static partial class myVertexShaderKeys
    {
        public static readonly ObjectParameterKey<SamplerState> mySampler = ParameterKeys.NewObject<SamplerState>();
        public static readonly ObjectParameterKey<Texture> myTex = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Buffer> verts = ParameterKeys.NewObject<Buffer>();
    }
}
